[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version"
[build]
  publish = "docs/.vitepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store --frozen-lockfile && npm run docs:build"
  ignore = "./scripts/docs-check.sh"
